- name: add apt key
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
    state: present

- name: add apt repository
  apt_repository:
    repo: deb http://pkg.jenkins.io/debian-stable binary/
    state: present
    update_cache: yes

- name: install jenkins
  apt:
    name: jenkins={{ jenkins.version }}
    state: present

- name: copy jenkins default
  template:
    src: etc/default/jenkins.j2
    dest: /etc/default/jenkins
    owner: jenkins
    group: jenkins
    mode: '0755'

- name: copy config.xml
  template:
    src: var/lib/jenkins/config.xml.j2
    dest: /var/lib/jenkins/config.xml
    owner: jenkins
    group: jenkins
    mode: '0755'

- name: jenkins restart
  service:
    name: jenkins
    state: restarted
